backend:
  name: github
  repo: growwithboss/portfolio
  branch: main
  auth_scope: repo
  auth_provider: github

publish_mode: editorial_workflow

media_folder: "images/blog" 
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "BOSS Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Post Title", name: "title", widget: "string", required: true}
      - {label: "Post SLUG (URL ID)", name: "slug", widget: "string", required: true, hint: "Use lower-case words separated by hyphens (e.g., new-strategies)."}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mm:ssZ", required: true}
      - {label: "Author", name: "author", widget: "string", default: "The BOSS Team"}
      - {label: "Body", name: "body", widget: "markdown", required: true}
